name: Create PDF

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pipenv'

      - name: Setup Pipenv
        uses: tiagovrtr/actions-pipenv@v1

      - name: Setup dependencies
        run: pipenv sync

      - name: Run generator
        run: pipenv run python generate.py --input=resume.tex

      - name: Generate RU PDF
        uses: hspaans/latexmk-action@v1
        with:
          format: pdf
          filename: resume.ru_RU.tex

      - name: Generate EN PDF
        uses: hspaans/latexmk-action@v1
        with:
          format: pdf
          filename: resume.en_EN.tex

      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Resume
          path: |
            resume.ru_RU.pdf
            resume.en_EN.pdf
