name: Create PDF

on:
  push:
    branches:
      - "*"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate PDF
        uses: hspaans/latexmk-action@v1
        with:
          format: pdf
          filename: resume.tex

      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Resume
          path: resume.pdf
