name: Publish PDF

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install gettext
        run: sudo apt-get install -y gettext

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pipenv'

      - name: Setup Pipenv
        uses: tiagovrtr/actions-pipenv@v1

      - name: Setup dependencies
        run: pipenv sync

      - name: Run generator
        run: pipenv run generate

      - name: Generate RU PDF
        uses: hspaans/latexmk-action@v1
        with:
          format: pdf
          filename: resume.ru_RU.tex

      - name: Generate EN PDF
        uses: hspaans/latexmk-action@v1
        with:
          format: pdf
          filename: resume.en_US.tex

      - name: Publish a release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            resume.ru_RU.pdf
            resume.en_US.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
