name: Publish PDF

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install gettext
        run: sudo apt-get install -y gettext

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Run generator
        run: uv run scripts/generate.py --input resume.tex

      - name: Generate RU PDF
        uses: hspaans/latexmk-action@v1
        with:
          format: pdf
          filename: resume.ru_RU.tex

      - name: Generate EN PDF
        uses: hspaans/latexmk-action@v1
        with:
          format: pdf
          filename: resume.en_US.tex

      - name: Publish a release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            resume.ru_RU.pdf
            resume.en_US.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
